Repository buzzfeed/sso, pull requests merged in 2018-10, with the labels that each got.

#77 pkg/aead: add explicit data race and locking to resolve
  internal/pkg/aead/aead.go
  internal/pkg/aead/aead_test.go
Labels: in progress

#56 simplify secret validation
  internal/auth/authenticator.go
  internal/auth/authenticator_test.go
  internal/auth/options.go
  internal/auth/options_test.go
  internal/pkg/aead/aead_test.go
  internal/pkg/sessions/cookie_store.go
  internal/pkg/sessions/cookie_store_test.go
  internal/pkg/sessions/session_state_test.go
  internal/proxy/oauthproxy.go
  internal/proxy/oauthproxy_test.go
  internal/proxy/options.go
  internal/proxy/options_test.go
  internal/proxy/providers/session_state_test.go
  quickstart/docker-compose.yml
Labels: in review

#89 bump golint to golang.org/x/lint/golint
  .circleci/config.yml
Labels: bug, in progress

#88 sso-proxy: adding an optional PROXY_PROVIDER_URL for split dns deployments
  internal/proxy/options.go
  internal/proxy/options_test.go
  internal/proxy/providers/provider_data.go
  internal/proxy/providers/sso.go
  internal/proxy/providers/sso_test.go
  quickstart/docker-compose.yml
Labels: in review
