Repository buzzfeed/sso, pull requests merged in 2018-11, with the labels that each got.

#87 sso-proxy: remove default provider and unused functions
  internal/proxy/oauthproxy.go
  internal/proxy/oauthproxy_test.go
  internal/proxy/providers/internal_util.go
  internal/proxy/providers/internal_util_test.go
  internal/proxy/providers/provider_data.go
  internal/proxy/providers/provider_default.go
  internal/proxy/providers/provider_default_test.go
  internal/proxy/providers/providers.go
  internal/proxy/providers/singleflight_middleware.go
  internal/proxy/providers/sso.go
  internal/proxy/providers/test_provider.go
Labels: in progress

#114 CONTRIBUTING: added merge policy language
  CONTRIBUTING.md
Labels: in progress

#124 docs: update email address in CoC
  CODE_OF_CONDUCT.md
Labels: chore, docs

#106 sso-proxy: sign upstream requests with a verifiable digital signature
  internal/proxy/oauthproxy.go
  internal/proxy/oauthproxy_test.go
  internal/proxy/options.go
  internal/proxy/proxy_config.go
  internal/proxy/request_signer.go
  internal/proxy/request_signer_test.go
  internal/proxy/testdata/private_key.pem
  internal/proxy/testdata/public_key.pub
Labels: enhancement

#120 quickstart: remove references to OLD_COOKIE_SECRET
  quickstart/docker-compose.yml
  quickstart/kubernetes/sso-auth-deployment.yml
Labels: chore, in progress

#119 Godeps: remove unused dependencies
  Godeps
Labels: chore, in progress

#123 sso-proxy: internal host should apply to redeem, /refresh, /validate, /profile
  internal/proxy/options.go
  internal/proxy/options_test.go
  internal/proxy/providers/provider_data.go
  internal/proxy/providers/sso.go
  internal/proxy/providers/sso_test.go
  quickstart/docker-compose.yml
  quickstart/kubernetes/sso-proxy-deployment.yml
Labels: in progress
