Repository buzzfeed/sso, pull requests merged in 2019-04, with the labels that each got.

#95 sso-proxy: avoid oversized cookies
  internal/pkg/aead/aead.go
Labels: enhancement

#179 proxy/request signers: request signers should also sign access token
  internal/proxy/oauthproxy.go
  internal/proxy/request_signer.go
Labels: bug, security/low-sev

#178 pkg/logging: resolve timestamp bug
  internal/pkg/logging/logging.go
Labels: bug
